In [1]:
import numpy as np

In [ ]:
a = np.array([23, 44, 67])
b = np.array([[22,33,44], [66,77,88]])

In [ ]:
print(a)

[23 44 67]


In [ ]:
print(b)

[[22 33 44]
 [66 77 88]]


In [ ]:
z = np.zeros((3,5))

print(z)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
o = np.ones((3,5))

print(o)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
r = np.random.rand(3,4)

print(r)

[[0.7267584  0.32343416 0.56091612 0.82797275]
 [0.74976402 0.47383192 0.07152911 0.04067023]
 [0.79306365 0.30695497 0.67752103 0.80456098]]


In [ ]:
i = np.eye(5)

print(i)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
print(a.shape)
print(b.shape)
print(a.ndim)
print(b.ndim)
print(a.size)
print(b.size)
print(a.dtype)
print(b.dtype)

(3,)
(2, 3)
1
2
3
6
int64
int64
